packages:
  - "nuxt"
  - "nuxt/*"
  - "react"
  - "react/*"
  - "solid"
  - "solid/*"
  - "svelte"
  - "svelte/*"
  - "tanstack"
  - "tanstack/*"
  - "vinext"
  - "vinext/*"
  - "vue"
  - "vue/*"

catalog:
  "@module-federation/vite": "1.13.0"
